name: Build OpenWrt IPK Package

on:
  push:
    tags: ['v*']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build using OpenWrt SDK
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        tags: kid-control-builder:latest
        outputs: type=local,dest=./artifacts
        build-args: |
          OPENWRT_SDK_URL=https://downloads.openwrt.org/snapshots/targets/armsr/armv8/openwrt-sdk-armsr-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz

    - name: List artifacts
      run: ls -la artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kid-control-ipk
        path: artifacts/*.ipk

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.ipk
